### ISSUE TITLE
Bug: Final Bowser Battle crashes when playing on a JP build of SM64.

### ISSUE THREAD

**Issue by MarioSpore** [ArchipelagoMW/Archipelago#3276]
### What happened?

Upon starting dialogue with final Bowser battle stage, the game suddenly crashes and closes immediately. I tested this on the US build and it did allow be to battle him. The only flags I had enabled for the JP build were` j8 BETTERCAMERA=1 TEXTURE_FIX=1 DISCORDRPC=1 EXTERNAL_DATA=1`. And even then I don't believe it is the main culprit. My only guess is that it is a faulty rom? My US build did not include any additional makeflags as well if it ends up being the issue.

This is the .yaml file I used that the host used to have my game run on their server:

```
Super Mario 64:
  progression_balancing: 50
  accessibility: items
  area_rando: off
  buddy_checks: 'true'
  exclamation_boxes: 1ups_only
  progressive_keys: 'true'
  enable_coin_stars: 'false'
  enable_move_rando: 'true'
  move_rando_actions:
    - Triple Jump
    - Long Jump
    - Backflip
    - Side Flip
    - Wall Kick
    - Dive
    - Ground Pound
    - Kick
    - Climb
    - Ledge Grab
  strict_cap_requirements: 'true'
  strict_cannon_requirements: 'true'
  strict_move_requirements: 'true'
  amount_of_stars: 120
  first_bowser_star_door_cost: 20
  basement_star_door_cost: 33
  second_floor_star_door_cost: 67
  mips1_cost: 12
  mips2_cost: 42
  stars_to_finish: 75
  death_link: 'false'
  completion_type: all_bowser_stages
description: 'Generated by https://archipelago.gg.'
game: Super Mario 64
name: MarioSpore
```

### What were the expected results?

I was expecting to be able to fight Bowser and pass the dialogue on the JP build like I would normally when I was on the US build.

### Software

While playing
