### ISSUE TITLE
Clique: Add support for plando text

### ISSUE THREAD

**Issue by josephwhite** [ArchipelagoMW/Archipelago#4184]
### What feature would you like to see?

I am aware of the google form to submit texts to the global array, but I am curious if its possible to add quotes supplied by the user via [plando text](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/alttp/docs/plando_en.md#texts). No plando text in the user yaml would just pull quotes from the global array.

```yaml
plando_texts:
  - text: "IN BK, AS PLANDO'D."
    at:
      locked: 1
```
![ArchipelagoMW-CliquePlandoText(POC)](https://github.com/user-attachments/assets/b8e58ae0-70bc-4796-b6a3-8b7f03982114)
