### ISSUE TITLE
Bug: Items become unhintable if they land in a location in someone else's world that's been hinted in your own

### ISSUE THREAD

**Issue by KScl** [ArchipelagoMW/Archipelago#4654]
This appears to have been introduced by the Hint Priorities PR, as I cannot replicate this bug in 0.5.1, only in main. Once an item has been hinted that lands in a player's world, that player cannot hint any items of theirs that land in that location in other people's worlds; if they attempt to do so, they will be given the previously hinted item in that location in their own world. This happens both for clients attempting to `!hint` for their own items, and the server attempting to hint for items for that player.

Test case YAML:

```yaml
name: Debugger1
game: A Link to the Past
requires:
  plando: items

A Link to the Past:
  plando_items:
  - item: Fire Rod
    location: Bottle Merchant
    world: Debugger2
  start_location_hints:
  - "Bottle Merchant"

---

name: Debugger2
game: A Link to the Past
requires:
  plando: items

A Link to the Past:
  plando_items:
  - item: Pegasus Boots
    location: Bottle Merchant
    world: Debugger1
```

This YAML places Debugger1's Fire Rod at Debugger2's Bottle Merchant, and Debugger2's Pegasus Boots pre-hinted at Debugger1's Bottle Merchant. You will be unable to hint for Debugger1's Fire Rod in any way, because the hint for Debugger2's Pegasus Boots will be treated as a "previous hint" when you attempt to do so.

```
/hint Debugger1 Fire Rod
Notice (Team #1): [Hint]: Debugger2's Pegasus Boots is at Bottle Merchant in Debugger1's World. (unspecified)
```
